import { useMemo, useState } from 'react';
import { ArrowRight, Check, ChevronDown, Gem, Instagram, Mail, MapPin, Menu, MessageCircle, Phone, Sparkles, Star, X } from 'lucide-react';
import { SERVICES_DATA, GALLERY_ITEMS } from './services';
import { RESIN_PRODUCTS } from './resinProducts';

const nav = ['Home','Resin Art','Printing','Gallery','About','Contact'];
const wa = 'https://wa.me/918112191408?text=Hello%20Sangram%20Resin%20Art%2C%20I%20want%20a%20custom%20quote.';

function App(){
 const [menu,setMenu]=useState(false), [filter,setFilter]=useState('all'), [quote,setQuote]=useState(false), [faq,setFaq]=useState<number|null>(null);
 const gallery = useMemo(()=>filter==='all'?GALLERY_ITEMS:GALLERY_ITEMS.filter(x=>x.category===filter),[filter]);
 const scroll=(id:string)=>{document.getElementById(id)?.scrollIntoView({behavior:'smooth'});setMenu(false)};
 return <div className="site">
  <header className="header"><div className="container nav"><button className="brand" onClick={()=>scroll('home')}><span className="brand-mark"><Gem size={20}/></span><span><b>SANGRAM</b><small>RESIN ART</small></span></button>
   <nav className={menu?'mobile-open':''}>{nav.map((n,i)=><button key={n} onClick={()=>scroll(i===0?'home':n.toLowerCase().replace(' ','-'))}>{n}</button>)}<button className="nav-cta" onClick={()=>setQuote(true)}>Get a Quote <ArrowRight size={16}/></button></nav>
   <button className="menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button>
  </div></header>
  <main>
   <section id="home" className="hero"><div className="hero-orb one"/><div className="hero-orb two"/><div className="container hero-grid"><div className="hero-copy"><div className="eyebrow"><Sparkles size={15}/> PREMIUM HANDCRAFTED STUDIO</div><h1>Memories,<br/><em>made permanent.</em></h1><p>Luxury resin art, personalized gifts, name plates and professional printing — designed around your story and finished with obsessive attention to detail.</p><div className="hero-actions"><button className="gold-btn" onClick={()=>setQuote(true)}>Start a Custom Order <ArrowRight size={18}/></button><button className="ghost-btn" onClick={()=>scroll('gallery')}>View our work</button></div><div className="trust"><span><Check/> Handmade</span><span><Check/> Custom designs</span><span><Check/> Premium finish</span></div></div><div className="hero-art"><div className="art-frame"><img src="/images/resin-art.svg" alt="Signature resin art"/><div className="art-overlay"/></div><div className="art-card"><span>01 / SIGNATURE</span><b>Resin art<br/>with a story.</b><small>Made in Odisha</small></div></div></div></section>
   <section className="marquee"><div>RESIN ART <i>✦</i> CUSTOM GIFTS <i>✦</i> NAME PLATES <i>✦</i> PREMIUM PRINTING <i>✦</i> SIGNAGE <i>✦</i> RESIN ART <i>✦</i></div></section>
   <section id="resin-art" className="section"><div className="container"><div className="section-head"><div><span className="eyebrow">THE STUDIO</span><h2>Crafted for people<br/><em>who value detail.</em></h2></div><p>Choose a ready concept or bring your own idea. We help with design, materials, size, finish and personalization from start to finish.</p></div><div className="feature-grid">{RESIN_PRODUCTS.map((p,i)=><article className="product-card" key={p.id}><div className="product-img"><img src={p.image} alt={p.title}/><span>0{i+1}</span></div><div className="product-body"><div className="tag">{p.categoryLabel}</div><h3>{p.title}</h3><p>{p.shortDesc}</p><button onClick={()=>setQuote(true)}>Customize this <ArrowRight size={15}/></button></div></article>)}</div></div></section>
   <section id="printing" className="dark-section"><div className="container service-layout"><div><span className="eyebrow">DESIGN + PRINT</span><h2>Make your brand<br/><em>impossible to miss.</em></h2><p>From banners and shop boards to visiting cards, wedding invitations and photo printing — one studio for your complete visual identity.</p><button className="gold-btn" onClick={()=>setQuote(true)}>Request a printing quote <ArrowRight size={18}/></button><div className="print-badges"><span>FAST TURNAROUND</span><span>PREMIUM FINISH</span><span>CUSTOM SIZES</span></div></div><div className="service-list">{SERVICES_DATA.filter(p=>p.category==='printing-banner').slice(0,6).map((p,i)=><div className="service-row" key={p.id}><span>{String(i+1).padStart(2,'0')}</span><div><b>{p.title}</b><small>{p.shortDesc}</small><small className="service-meta">{p.popularSizes} • {p.turnaroundTime}</small></div><button className="service-order" onClick={()=>setQuote(true)}><ArrowRight size={18}/></button></div>)}</div></div></section>
   <section className="process section"><div className="container"><div className="section-head"><div><span className="eyebrow">HOW IT WORKS</span><h2>Simple process.<br/><em>Beautiful result.</em></h2></div></div><div className="process-grid">{[['01','Share your idea','Send us your photo, name, size or reference.'],['02','Approve the design','We discuss materials, colors, layout and finish.'],['03','We craft & print','Your order is produced with careful quality checks.'],['04','Collect / receive','Pickup or delivery is arranged when ready.']].map(x=><div className="process-card" key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></div>)}</div></div></section>
   <section id="gallery" className="section gallery-section"><div className="container"><div className="section-head"><div><span className="eyebrow">SELECTED WORK</span><h2>A gallery of<br/><em>made-to-order.</em></h2></div><div className="filters">{[['all','All'],['resin','Resin'],['banners','Banners'],['boards','Boards'],['stationery','Cards']].map(([v,l])=><button className={filter===v?'active':''} onClick={()=>setFilter(v)} key={v}>{l}</button>)}</div></div><div className="gallery-grid">{gallery.map((g,i)=><article className={'gallery-item g'+i} key={g.id}><img src={g.image} alt={g.title}/><div><span>{g.categoryLabel}</span><h3>{g.title}</h3></div></article>)}</div></div></section>
   <section id="about" className="about"><div className="container about-grid"><div className="about-number">01<span>/</span>04</div><div><span className="eyebrow">WHY SANGRAM</span><h2>A small studio.<br/><em>A big obsession.</em></h2><p>We believe personalized art should feel personal — not mass-produced. Every resin piece and every printed design starts with your idea and is finished for your exact occasion, space or business.</p><div className="stats"><div><b>100%</b><span>Hand finished</span></div><div><b>Custom</b><span>Made to order</span></div><div><b>Premium</b><span>Materials</span></div></div></div></div></section>
   <section className="faq section"><div className="container faq-grid"><div><span className="eyebrow">QUESTIONS</span><h2>Before you<br/><em>order.</em></h2></div><div>{[['Do you make fully customized resin designs?','Yes. Names, colors, photos, flowers, shapes, sizes and finishing can be customized.'],['Can I order printing and design together?','Yes. We provide design + printing for banners, shop boards, cards, invitations, posters and more.'],['How do I get a price?','Send your size, quantity, reference/photo and required date on WhatsApp. We will discuss the suitable option and quote.'],['Do you offer pickup?','Orders can be coordinated for studio pickup; delivery can be discussed depending on the order and location.']].map(([q,a],i)=><div className="faq-row" key={q}><button onClick={()=>setFaq(faq===i?null:i)}><span>{q}</span>{faq===i?<X size={18}/>:<ChevronDown size={18}/>}</button>{faq===i&&<p>{a}</p>}</div>)}</div></div></section>
   <section id="contact" className="contact"><div className="container contact-box"><div><span className="eyebrow">LET'S MAKE SOMETHING</span><h2>Have an idea?<br/><em>Let's make it real.</em></h2><p>Tell us what you want to create. We'll help with design, materials, size and finishing.</p></div><div className="contact-actions"><a href={wa} target="_blank"><MessageCircle/> WhatsApp us</a><a href="tel:+918112191408"><Phone/> 81121 91408</a><a href="mailto:sangramresinart@gmail.com"><Mail/> Email studio</a></div></div></section>
  </main>
  <a className="floating-wa" href={wa} target="_blank" aria-label="WhatsApp"><MessageCircle/></a>
  <footer><div className="container footer-grid"><div><div className="brand footer-brand"><span className="brand-mark"><Gem size={20}/></span><span><b>SANGRAM</b><small>RESIN ART</small></span></div><p>Handmade resin art, customized gifts & professional printing from Odisha.</p></div><div><b>Explore</b><button onClick={()=>scroll('resin-art')}>Resin Art</button><button onClick={()=>scroll('printing')}>Printing</button><button onClick={()=>scroll('gallery')}>Gallery</button></div><div><b>Studio</b><span><MapPin/> Odisha, India</span><a href="tel:+918112191408"><Phone/> 81121 91408</a><a href={wa} target="_blank"><MessageCircle/> WhatsApp</a><a href="https://www.instagram.com/" target="_blank"><Instagram/> Instagram</a></div></div><div className="copyright">© 2026 Sangram Resin Art <span>•</span> Handmade with intention.</div></footer>
  {quote&&<div className="modal" onClick={()=>setQuote(false)}><div className="modal-card" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setQuote(false)}><X/></button><span className="eyebrow">CUSTOM ORDER</span><h2>Let's create your piece.</h2><p>Send your requirements, photo or reference on WhatsApp and we'll discuss the design, size and price.</p><a className="gold-btn full" href={wa} target="_blank"><MessageCircle/> Continue on WhatsApp</a><a className="ghost-btn full" href="tel:+918112191408"><Phone/> Call the studio</a></div></div>}
 </div>
}
export default App;
